### ISSUE TITLE
Simplify installation procedure

### ISSUE THREAD

**Issue by ZtereoHYPE** [J-onasJones/PinBoardBot#1]
It is common for node programs to actually include in the repository the package.json file, which would allow installation of dependencies with the standard `npm i` instead of having to list them.

**Comment by JonasunderscoreJones** [comment]
I do include the package.json file. so the `npm i` command replaces the command I have put to install the dependencies?

**Comment by ZtereoHYPE** [comment]
your package.json seems to be slightly off and thus not functioning correctly with npm's tools... let me fix that in a PR

**Comment by JonasunderscoreJones** [comment]
sure, that' be nice thanks!
